import { useEffect, useMemo, useState } from 'react';
import type { GameState, RpStateContainer, StateEvent } from './types';
import { emptyState, getContainer, preferences } from './persistence';
import { gameStateSchema, manualEventsSchema } from './schema';
import type { RpStateMachine, TavernContext } from './runtime';
import './styles.css';

export function StateApp({ runtime, getContext }: { runtime: RpStateMachine; getContext: () => TavernContext }) {
  const [, redraw] = useState(0); const [open, setOpen] = useState(false); const [tab, setTab] = useState('Overview');
  const context = getContext(); const container = getContainer(context); const malformed = context.chatMetadata.rp_state_machine !== undefined && !container; const prefs = preferences(context);
  const defaultTime = useMemo(() => { const d = new Date(), p = (n: number) => String(n).padStart(2, '0'); return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`; }, []);
  const [dateTime, setDateTime] = useState(defaultTime), [location, setLocation] = useState(''), [seedJson, setSeedJson] = useState('');
  const refresh = () => redraw(n => n + 1);
  const seed = async () => { if (!dateTime || !location.trim()) return; try { const state = emptyState(dateTime, location.trim()); const fragment = seedJson.trim() ? JSON.parse(seedJson) : {}; if (!fragment || typeof fragment !== 'object' || Array.isArray(fragment)) throw new Error('fragment'); const input = fragment as Partial<GameState>; const merged: GameState = { ...state, ...input, world: { ...state.world, ...input.world, localDateTime: dateTime, location: location.trim() }, player: { ...state.player, ...input.player }, currencies: input.currencies ?? state.currencies, inventory: input.inventory ?? state.inventory, characters: input.characters ?? state.characters }; const valid = gameStateSchema.safeParse(merged); if (!valid.success) throw new Error('invalid'); await runtime.seed(valid.data); refresh(); } catch { alert('Optional seed JSON must be a valid GameState fragment.'); } };
  const change = async (events: StateEvent[], explanation: string) => { await runtime.manual(events, explanation); refresh(); };
  return <>
    <button className="menu_button" data-rpstate-open onClick={() => { setOpen(true); refresh(); }} title="Open RP State Machine">State</button>
    {open && <aside className="rpstate-drawer" aria-label="RP State Machine">
      <header><h2>RP State</h2><button aria-label="Close" onClick={() => setOpen(false)}>×</button></header>
      {!container ? <section className="rpstate-seed"><h3>{malformed ? 'Stored state needs reset' : 'Seed this chat'}</h3>{malformed && <p className="rpstate-review">The saved state failed schema validation. Export/repair it externally or confirm a new seed below.</p>}<p>State tracking begins only after you confirm a baseline.</p><label>Local date/time<input type="datetime-local" value={dateTime} onChange={e => setDateTime(e.target.value)} required /></label><label>Location<input value={location} onChange={e => setLocation(e.target.value)} required /></label><label>Optional currencies, inventory, player conditions, and characters JSON<textarea value={seedJson} onChange={e => setSeedJson(e.target.value)} placeholder={'{"currencies":{"gold":{"id":"gold","name":"Gold","amount":10}},"player":{"conditions":["tired"]},"characters":{}}'} /></label><button className="menu_button" onClick={seed}>Save baseline</button></section> : <>
        <nav>{['Overview', 'Inventory', 'Characters', 'History & Review', 'Settings'].map(x => <button className={tab === x ? 'active' : ''} onClick={() => setTab(x)} key={x}>{x}</button>)}</nav>
        {tab === 'Overview' && <Overview state={container.currentState} status={container.status} onChange={change} />}
        {tab === 'Inventory' && <Inventory state={container.currentState} onChange={change} />}
        {tab === 'Characters' && <Characters state={container.currentState} onChange={change} />}
        {tab === 'History & Review' && <History container={container} context={context} runtime={runtime} refresh={refresh} />}
        {tab === 'Settings' && <Settings context={context} runtime={runtime} prefs={prefs} refresh={refresh} />}
      </>}
    </aside>}
  </>;
}
function Overview({ state, status, onChange }: { state: GameState; status: string; onChange: (e: StateEvent[], note: string) => Promise<void> }) { const [time, setTime] = useState(state.world.localDateTime), [location, setLocation] = useState(state.world.location), [currency, setCurrency] = useState(''), [amount, setAmount] = useState(0), [condition, setCondition] = useState(''); useEffect(() => { setTime(state.world.localDateTime); setLocation(state.world.location); }, [state.world.localDateTime, state.world.location]); return <section><p className="rpstate-status">{status}</p><label>Date/time<input type="datetime-local" value={time} onChange={e => setTime(e.target.value)} /></label><label>Location<input value={location} onChange={e => setLocation(e.target.value)} /></label><button onClick={() => onChange([{ type: 'time.set', localDateTime: time }, { type: 'location.set', location }], 'Manual world edit')}>Save world</button><dl><dt>Currencies</dt><dd>{Object.values(state.currencies).map(x => `${x.name}: ${x.amount}`).join(', ') || 'None'}</dd><dt>Player conditions</dt><dd>{state.player.conditions.join(', ') || 'None'}</dd></dl><label>Currency<input value={currency} onChange={e => setCurrency(e.target.value)} /></label><label>Amount<input type="number" step="1" value={amount} onChange={e => setAmount(Number(e.target.value))} /></label><button onClick={() => currency && onChange([{ type: 'currency.set', currency, name: currency, amount }], 'Manual currency edit')}>Save currency</button><label>Player condition<input value={condition} onChange={e => setCondition(e.target.value)} /></label><button onClick={() => condition && onChange([{ type: 'condition.add', target: 'player', condition }], 'Manual player condition edit')}>Add condition</button></section>; }
function Inventory({ state, onChange }: { state: GameState; onChange: (e: StateEvent[], note: string) => Promise<void> }) { const [search, setSearch] = useState(''); const [item, setItem] = useState(''); const [quantity, setQuantity] = useState(1); const visible = Object.values(state.inventory).filter(x => x.name.toLowerCase().includes(search.toLowerCase())); return <section><input aria-label="Search inventory" placeholder="Search" value={search} onChange={e => setSearch(e.target.value)} /><ul>{visible.map(x => <InventoryRow key={x.id} item={x} onChange={onChange} />)}</ul><h3>Add item</h3><input placeholder="Item" value={item} onChange={e => setItem(e.target.value)} /><input aria-label="Quantity" type="number" min="1" value={quantity} onChange={e => setQuantity(Number(e.target.value))} /><button onClick={() => item && onChange([{ type: 'inventory.add', item, quantity, name: item }], 'Manual inventory edit')}>Add</button></section>; }
function InventoryRow({ item, onChange }: { item: GameState['inventory'][string]; onChange: (e: StateEvent[], note: string) => Promise<void> }) { const [quantity, setQuantity] = useState(item.quantity); const [note, setNote] = useState(item.note ?? ''); useEffect(() => { setQuantity(item.quantity); setNote(item.note ?? ''); }, [item.quantity, item.note]); return <li><strong>{item.name}</strong><input aria-label={`${item.name} quantity`} type="number" min="0" step="1" value={quantity} onChange={e => setQuantity(Number(e.target.value))} /><input aria-label={`${item.name} note`} placeholder="Note" value={note} onChange={e => setNote(e.target.value)} /><button onClick={() => onChange([{ type: 'inventory.set', item: item.id, quantity, note }], 'Manual inventory edit')}>Save</button></li>; }
function Characters({ state, onChange }: { state: GameState; onChange: (e: StateEvent[], note: string) => Promise<void> }) { const [id, setId] = useState(''), [name, setName] = useState(''); return <section>{Object.values(state.characters).map(x => <CharacterEditor key={x.id} character={x} onChange={onChange} />)}<h3>Add character</h3><input placeholder="Stable id" value={id} onChange={e => setId(e.target.value)} /><input placeholder="Display name" value={name} onChange={e => setName(e.target.value)} /><button onClick={() => id && name && onChange([{ type: 'character.set', id, displayName: name, aliases: [], conditions: [] }], 'Manual character creation')}>Add character</button></section>; }
function CharacterEditor({ character, onChange }: { character: GameState['characters'][string]; onChange: (e: StateEvent[], note: string) => Promise<void> }) { const [score, setScore] = useState(character.relationship.score), [note, setNote] = useState(character.relationship.note ?? ''), [condition, setCondition] = useState(''), [aliases, setAliases] = useState(character.aliases.join(', ')); useEffect(() => { setScore(character.relationship.score); setNote(character.relationship.note ?? ''); setAliases(character.aliases.join(', ')); }, [character.relationship.score, character.relationship.note, character.aliases]); return <article><h3>{character.displayName}</h3><label>Aliases<input value={aliases} onChange={e => setAliases(e.target.value)} /></label><button onClick={() => onChange([{ type: 'character.set', id: character.id, displayName: character.displayName, aliases: aliases.split(',').map(x => x.trim()).filter(Boolean), conditions: character.conditions, relationshipScore: character.relationship.score, relationshipNote: character.relationship.note }], 'Manual alias edit')}>Save aliases</button><p>Conditions: {character.conditions.join(', ') || '—'}</p>{character.relationship.lastReason && <p>Recent change: {character.relationship.lastReason}</p>}<label>Relationship score<input type="number" min="-100" max="100" step="1" value={score} onChange={e => setScore(Number(e.target.value))} /></label><label>Relationship note<input value={note} onChange={e => setNote(e.target.value)} /></label><button onClick={() => onChange([{ type: 'relationship.set', character: character.id, score, note, reason: 'Manual relationship edit' }], 'Manual relationship edit')}>Save relationship</button><label>Add condition<input value={condition} onChange={e => setCondition(e.target.value)} /></label><button onClick={() => condition && onChange([{ type: 'condition.add', target: character.id, condition }], 'Manual character condition edit')}>Add condition</button><button onClick={() => onChange([{ type: 'relationship.adjust', character: character.id, amount: 1, reason: 'Manual adjustment' }], 'Manual relationship edit')}>+1</button><button onClick={() => onChange([{ type: 'relationship.adjust', character: character.id, amount: -1, reason: 'Manual adjustment' }], 'Manual relationship edit')}>−1</button></article>; }
function History({ container, runtime, refresh }: { container: RpStateContainer; context: TavernContext; runtime: RpStateMachine; refresh: () => void }) { return <section><button onClick={() => runtime.retry().then(refresh)}>Replay / retry</button><h3>Transactions</h3><ol>{container.transactions.map(t => <li key={t.id}><strong>{t.origin}</strong>: {t.explanation || `${t.events.length} event(s)`}</li>)}</ol><h3>Review</h3>{container.reviewQueue.length ? container.reviewQueue.map(r => <ReviewEditor key={r.id} item={r} runtime={runtime} refresh={refresh} />) : <p>Nothing to review.</p>}</section>; }
function ReviewEditor({ item, runtime, refresh }: { item: RpStateContainer['reviewQueue'][number]; runtime: RpStateMachine; refresh: () => void }) { const [raw, setRaw] = useState(JSON.stringify(item.transaction?.events ?? [], null, 2)); useEffect(() => setRaw(JSON.stringify(item.transaction?.events ?? [], null, 2)), [item.id, item.transaction]); const apply = async () => { try { const parsed = manualEventsSchema.safeParse(JSON.parse(raw)); if (!parsed.success) return alert('Events JSON is invalid.'); await runtime.applyReviewedEvents(item.id, parsed.data); refresh(); } catch { alert('Reviewed events were not applied; details remain in review.'); } }; return <article className="rpstate-review"><p>{item.message}</p>{item.raw && <details><summary>Rejected extractor output</summary><pre>{item.raw}</pre></details>}<textarea aria-label="Review events JSON" value={raw} onChange={e => setRaw(e.target.value)} /><button onClick={() => runtime.retry().then(refresh)}>Retry extraction</button><button onClick={apply}>Edit & apply</button><button onClick={() => runtime.discardReview(item.id).then(refresh)}>Discard</button></article>; }
function Settings({ context, runtime, prefs, refresh }: { context: TavernContext; runtime: RpStateMachine; prefs: ReturnType<typeof preferences>; refresh: () => void }) {
  const update = (patch: Partial<typeof prefs>) => { context.extensionSettings.rp_state_machine = { ...prefs, ...patch }; context.saveSettingsDebounced?.(); refresh(); };
  const exportState = () => { const blob = new Blob([JSON.stringify(getContainer(context), null, 2)], { type: 'application/json' }); const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = 'rp-state-machine.json'; a.click(); setTimeout(() => URL.revokeObjectURL(a.href), 0); };
  const importState = async (file?: File) => { if (!file || !confirm('Replace this chat state from the selected JSON?')) return; try { await runtime.importState(JSON.parse(await file.text())); refresh(); } catch (error) { alert(`Import rejected: ${String(error)}`); } };
  const reseed = () => { if (!confirm('Reseed from the current state and discard replay history?')) return; const c = getContainer(context); if (c) runtime.seed(c.currentState).then(refresh); };
  return <section><label><input type="checkbox" checked={!prefs.paused} onChange={e => update({ paused: !e.target.checked })} /> Extract changes</label><label><input type="checkbox" checked={prefs.injectionEnabled} onChange={e => update({ injectionEnabled: e.target.checked })} /> Prompt injection</label><label>Snapshot ceiling<input type="number" value={prefs.tokenCeiling} min="100" onChange={e => update({ tokenCeiling: Number(e.target.value) })} /></label><label><input type="checkbox" checked={prefs.debug} onChange={e => update({ debug: e.target.checked })} /> Debug logging</label><button onClick={exportState}>Export JSON</button><label>Import JSON<input type="file" accept="application/json" onChange={e => importState(e.target.files?.[0])} /></label><button onClick={reseed}>Reseed current state</button><button onClick={() => { if (confirm('Reset the state for this chat?')) runtime.resetState().then(refresh); }}>Reset</button><button onClick={() => runtime.command('replay')}>Replay</button></section>;
}
